version: "3"
services:
  jenkins:
    image: jenkins:test
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true -Djenkins.install.runSetupWizard=false"
    volumes:
      - /var/rundocker.sock:/var/run/docker.sock:rw
      - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /data/jenkins/vault:/var/jenkins_home/vault
    network_mode: "host"
